apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dockerapp-argo-application
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: "https://github.com/dsantafe/Bootcamp-Devops-Engineer"
    path: labs/lab-10-kubernetes-argocd/dev
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dockerapp-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
