Vagrant.configure("2") do |config|

    config.ssh.insert_key = false
    config.vm.box = "ubuntu/trusty64"

    # Virtualbox configuration
    config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
      #v.linked_clone = true
    end
  
    config.vm.define "node1" do |machine|
      machine.vm.network "private_network", ip: "172.17.177.21"
    end
  
    config.vm.define "node2" do |machine|
      machine.vm.network "private_network", ip: "172.17.177.22"
    end
  
    config.vm.define 'controller' do |machine|
      machine.vm.network "private_network", ip: "172.17.177.11"
      machine.vm.synced_folder "../ansible", "/ansible", :mount_options => ["dmode=700", "fmode=700"]
  
      machine.vm.provision :ansible_local do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.limit = "all"
        ansible.config_file = "/ansible/ansible.cfg"
        ansible.become = true
        ansible.playbook       = "/ansible/playbook.yml"
        ansible.inventory_path = "/ansible/hosts"        
      end
    end
  
  end
  