# Usa la imagen oficial de Apache HTTP Server como base
FROM httpd:latest

# Copia el archivo index.html a la carpeta de trabajo del contenedor
COPY ./index.html /usr/local/apache2/htdocs/

# Expone el puerto 8080
EXPOSE 8080
